# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.pb.dart'
    - '**/*.pbjson.dart'
    - '**/*.pbserver.dart'
    - '**/*.pbenum.dart'

linter:
  rules:
    - combinators_ordering
    - directives_ordering
    - prefer_interpolation_to_compose_strings
    - public_member_api_docs
    - require_trailing_commas

custom_lint:
  rules:
    - newline_before_return
    - cyclomatic_complexity:
        max_complexity: 12
    - function_lines_of_code:
        max_lines: 100
    - member_ordering:
      alphabetize: true
      order:
        - private_fields
        - public_fields
        - getters_setters
        - private_constructors
        - factory_constructors
        - public_constructors
        - initialize_method
        - overridden_methods
        - public_methods
        - private_methods
